// Daftar kota dan kabupaten di Indonesia
// Sumber: Badan Pusat Statistik (BPS) & sumber data terbuka lainnya.
export const cities = [
  "Jakarta Pusat",
  "Jakarta Utara",
  "Jakarta Barat",
  "Jakarta Selatan",
  "Jakarta Timur",
  "Surabaya",
  "Bandung",
  "Bekasi",
  "Medan",
  "Tangerang",
  "Depok",
  "Semarang",
  "Palembang",
  "Makassar",
  "Batam",
  "Pekanbaru",
  "Bogor",
  "Bandar Lampung",
  "Padang",
  "Denpasar",
  "Malang",
  "Samarinda",
  "Tasikmalaya",
  "Banjarmasin",
  "Balikpapan",
  "Pontianak",
  "Serang",
  "Jambi",
  "Cimahi",
  "Manado",
  "Kupang",
  "Cilegon",
  "Mataram",
  "Jayapura",
  "Yogyakarta",
  "Cirebon",
  "Ambon",
  "Bengkulu",
  "Palu",
  "Kendari",
  "Sukabumi",
  "Karawang",
  "Pekalongan",
  "Dumai",
  "Tegal",
  "Kediri",
  "Binjai",
  "Purwokerto",
  "Salatiga",
  "Pematangsiantar",
  "Tanjungpinang",
  "Gorontalo",
  "Madiun",
  "Batu",
  "Pasuruan",
  "Probolinggo",
  "Tanjungbalai",
  "Mojokerto",
  "Magelang",
  "Blitar",
  "Parepare",
  "Langsa",
  "Lhokseumawe",
  "Singkawang",
  "Banjarbaru",
  "Bitung",
  "Ternate",
  "Lubuklinggau",
  "Prabumulih",
  "Pagar Alam",
  "Sorong",
  "Metro",
  "Tidore Kepulauan",
  "Meulaboh",
  "Sabang",
  "Banda Aceh",
  "Subulussalam",
  "Tebing Tinggi",
  "Sibolga",
  "Gunungsitoli",
  "Padangsidimpuan",
  "Pariaman",
  "Payakumbuh",
  "Bukittinggi",
  "Padang Panjang",
  "Solok",
  "Sawahlunto",
  "Sungai Penuh",
  "Pangkal Pinang",
  "Bontang",
  "Tarakan",
  "Bau-bau",
  "Kotamobagu",
  "Tomohon",
  "Palopo",
  "Banjar",
  "Biak",
  "Bondowoso",
  "Bima",
  "Baubau",
  "Gresik",
  "Jember",
  "Jombang",
  "Klaten",
  "Kudus",
  "Lamongan",
  "Lumajang",
  "Nganjuk",
  "Ngawi",
  "Pacitan",
  "Pamekasan",
  "Pati",
  "Ponorogo",
  "Purbalingga",
  "Purworejo",
  "Rembang",
  "Sampang",
  "Sidoarjo",
  "Situbondo",
  "Sragen",
  "Sumenep",
  "Trenggalek",
  "Tuban",
  "Tulungagung",
  "Ungaran",
  "Wonogiri",
  "Wonosobo"
];
