import type { BrandConfig } from './types';

/**
 * RMB — Rental Motor Bandung
 * This is the REFERENCE brand template for all other landings.
 */
export const rmbBrand: BrandConfig = {
  id: 'rmb',
  shortName: 'RMB',
  legalName: 'RMB Rental Motor Bandung',
  city: 'Bandung',
  tagline: 'Your Freedom to Explore Starts Here.',
  description:
    'Sewa motor matic di Bandung dengan mudah dan cepat. Harga terjangkau mulai 60rb, layanan terpercaya, unit siap pakai. Pesan sekarang!',
  siteUrl: 'https://rentalmotorbandungrmb.com',
  whatsappNumber: '6282329616166',
  gtmId: 'GTM-KM5GLHDW',
  adsId: 'AW-11380968042',
  logoPath: '/images/logo-rmb.webp',
  ogImagePath: '/images/hero1.webp',
  social: {
    instagram: 'https://www.instagram.com/inforentalmotorbandung/',
    tiktok: 'https://www.tiktok.com/@nethen.rental',
  },
  navLinks: [
    { href: '/armada', label: 'Armada' },
    { href: '/harga', label: 'Harga' },
    { href: '/galeri', label: 'Galeri' },
    { href: '/tentang-kami', label: 'Tentang Kami' },
    { href: '/lokasi', label: 'Lokasi' },
    { href: '/faq', label: 'FAQ' },
    { href: '/snk', label: 'S&K' },
  ],
  seoLocations: [
    { name: 'Sewa Motor Dago', href: '/sewa-motor-dago' },
    { name: 'Rental Motor Lembang', href: '/rental-motor-lembang' },
    { name: 'Sewa Motor Braga', href: '/sewa-motor-braga' },
    { name: 'Rental Motor Setiabudi', href: '/rental-motor-setiabudi' },
    { name: 'Sewa Motor Cihampelas', href: '/sewa-motor-cihampelas' },
    { name: 'Rental Motor Gedung Sate', href: '/rental-motor-gedung-sate' },
    { name: 'Sewa Motor Buahbatu', href: '/sewa-motor-buahbatu' },
    { name: 'Rental Motor Stasiun Bandung', href: '/rental-motor-stasiun-bandung' },
    { name: 'Sewa Motor Bandara Husein Sastranegara', href: '/sewa-motor-bandara-husein' },
  ],
  homepageSections: [
    'Header',
    'Hero',
    'About',
    'Fleet',
    'Process',
    'Pricing',
    'Testimonials',
    'FAQ',
    'OrderForm (#pesan)',
    'CTA',
    'Footer',
    'FloatingWhatsApp',
    'PromoPopup',
  ],
  promoPopup: {
    enabled: true,
    delayMs: 12000,
    eyebrow: 'Unit terbatas hari ini',
    title: 'Pesan sekarang, keburu kehabisan!',
    description:
      'Weekend & musim liburan unit cepat ludes. Amankan motor favorit Anda sekarang sebelum penuh.',
    primaryCta: 'Pesan Sekarang',
    secondaryCta: 'Chat WhatsApp',
    footnote: 'Respon cepat via WhatsApp · Antar jemput tersedia',
  },
  business: {
    streetAddress: 'Jl. Samiaji No.11A, Arjuna, Kec. Cicendo',
    addressLocality: 'Bandung',
    addressRegion: 'Jawa Barat',
    postalCode: '40172',
    addressCountry: 'ID',
    latitude: -6.892019,
    longitude: 107.587885,
    openingHours: 'Mo-Su 05:00-21:30',
    priceRange: 'Rp60.000+',
  },
  theme: {
    background: '43 67% 96%',
    foreground: '80 24% 9%',
    primary: '43 100% 54%',
    primaryForeground: '80 24% 9%',
    muted: '43 33% 91%',
    mutedForeground: '0 0% 40%',
    border: '43 33% 91%',
    ring: '43 100% 54%',
    radius: '0.625rem',
    fontSans: 'Inter',
    fontDisplay: 'Plus Jakarta Sans',
  },
};
